const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const fs = require('fs');

const userGamesList = [
  "60 Seconds! Reatomized",
  "A Plague Tale: Innocence",
  "A Plague Tale: Requiem",
  "A Quiet Place: The Road Ahead",
  "A Way Out",
  "ACE COMBAT™7: SKIES UNKNOWN",
  "ACE COMBAT™7: SKIES UNKNOWN - TOP GUN: Maverick Ultimate Edition",
  "Age of Empires II: Definitive Edition - Standard Edition",
  "Age of Mythology: Retold Standard Edition",
  "Alan Wake 2",
  "Alan Wake 2 Deluxe Edition",
  "Alan Wake Remastered",
  "Alone in the Dark",
  "Alien: Isolation",
  "Among Us",
  "AO Tennis 2",
  "ARC Raiders",
  "ARK: Survival Ascended",
  "ARK: Survival Evolved",
  "Arma Reforger",
  "Assassin's Creed Chronicles Trilogy",
  "Assassin's Creed® III: Remastered",
  "Assassin's Creed® Mythology pack",
  "Assassin's Creed Legendary Collection",
  "Assassin's Creed® Rogue Remastered",
  "Assassin’s Creed Shadows",
  "Assassin's Creed Shadows Digital Deluxe Edition",
  "Assassin's Creed Valhalla",
  "Assassin's Creed Valhalla - Complete Edition",
  "Assassin's Creed Valhalla - Ragnarök Edition",
  "Assassin's Creed® Mirage",
  "Assassin's Creed® Mirage Deluxe Edition",
  "Assassin's Creed® Odyssey",
  "Assassin's Creed® Odyssey Deluxe Edition",
  "Assassin's Creed® Odyssey Gold Edition",
  "Assassin's Creed® Origins",
  "Assassin's Creed® Origins - GOLD EDITION",
  "Assassin's Creed® Origins - DELUXE EDITION",
  "Assassin’s Creed Mirage & Assassin's Creed Valhalla Bundle",
  "Assassin’s Creed® Syndicate",
  "Assassin’s Creed® The Ezio Collection",
  "Assassin’s Creed® Unity",
  "Assassin’s Creed® Valhalla + Watch Dogs®: Legion Bundle",
  "Assetto Corsa",
  "Assetto Corsa Competizione",
  "Assetto Corsa Ultimate Edition",
  "ASTRO BOT",
  "ASTRO BOT Rescue Mission",
  "Astroneer - Evolution Edition",
  "Atomic Heart",
  "Avatar: Frontiers of Pandora™",
  "Back 4 Blood: Deluxe Edition",
  "Back 4 Blood: Standard Edition",
  "Back 4 Blood: Ultimate Edition",
  "Baldur's Gate 3",
  "Batman: Arkham Collection",
  "Batman: Arkham Knight",
  "Battlefield 4",
  "Battlefield V Definitive Edition",
  "Battlefield™ 1",
  "Battlefield™ 1 Revolution",
  "Battlefield™ 2042",
  "Battlefield™ 6 Standard Edition",
  "Battlefield™ Hardline Standard Edition",
  "Battlefield™ Hardline Ultimate Edition",
  "Battlefield™ V",
  "BioShock: The Collection",
  "BioShock Remastered",
  "Black Myth: Wukong",
  "Blasphemous + Blasphemous 2 Bundle",
  "Blasphemous 2 - Mea Culpa Edition",
  "Bloodborne™",
  "Bloodborne™ Complete Edition Bundle",
  "Bluey: The Videogame",
  "BODYCAMERA SHOOTER",
  "Borderlands 3",
  "Borderlands 3 Next Level Bundle",
  "Borderlands: Game of the Year Edition",
  "Bratz™: Flaunt Your Fashion",
  "BULLY",
  "Burnout™ Paradise Remastered",
  "Bus Driver Simulator",
  "Bus Simulator",
  "Bus Simulator 21 Next Stop",
  "Call of Duty®: Advanced Warfare Gold Edition",
  "Call of Duty®: Black Ops 4",
  "Call of Duty®: Black Ops 6",
  "Call of Duty®: Black Ops 6 - Vault Edition",
  "Call of Duty®: Black Ops 7",
  "Call of Duty®: Black Ops III - Zombies Chronicles Edition",
  "Call of Duty®: Ghosts Gold Edition",
  "Call of Duty®: Infinite Warfare",
  "Call of Duty®: Modern Warfare®",
  "Call of Duty®: Modern Warfare® (INGLES)",
  "Call of Duty®: Modern Warfare® 2 Campaign Remastered",
  "Call of Duty®: Modern Warfare® II - Cross-Gen Bundle",
  "Call of Duty®: Modern Warfare® III - Cross-Gen Bundle",
  "Call of Duty®: Modern Warfare® Remastered",
  "Call of Duty®: Vanguard",
  "Call of Duty®: WWII - Gold Edition (INGLES)",
  "Call of Duty®️: WWII - Gold Edition (LATINO)",
  "Captain Tsubasa: Rise of New Champions",
  "Captain Tsubasa: Rise of New Champions Deluxe Edition",
  "Captain Tsubasa: Rise of New Champions Ultimate Edition",
  "Car Mechanic Simulator 2021",
  "Cars 3: Driven to Win",
  "Castle Crashers Remastered",
  "Cities: Skylines - Remastered",
  "Clair Obscur: Expedition 33",
  "Clair Obscur: Expedition 33 – Deluxe Edition",
  "Control: Ultimate Edition",
  "Crash Bandicoot™ - Crashiversary Bundle",
  "Crash Bandicoot™ - Quadrilogy Bundle",
  "Crash Bandicoot™ Bundle - N. Sane Trilogy + CTR Nitro",
  "Crash Bandicoot™ N. Sane Trilogy",
  "Crash™ + Spyro™ Triple Play Bundle",
  "Crash™ Team Racing Nitro-Fueled",
  "Crash™ Team Racing Nitro-Fueled + Spyro™ Game Bundle",
  "Crysis 3 Remastered",
  "Crysis Remastered",
  "Crysis Remastered Trilogy",
  "Cult of the Lamb: Sinful Edition",
  "CUPHEAD",
  "Cyberpunk 2077",
  "Cyberpunk 2077: Ultimate Edition",
  "Dakar Desert Rally",
  "DARK SOULS™ II: Scholar of the First Sin",
  "DARK SOULS™ III",
  "Darksiders II Deathinitive Edition",
  "Darksiders III",
  "Days Gone",
  "Days Gone Remastered",
  "Dead by Daylight",
  "Dead Island 2",
  "Dead Island 2 Deluxe Edition",
  "Dead Island Definitive Collection",
  "Dead Island Definitive Edition",
  "Dead Island: Riptide Definitive Edition",
  "DEATH STRANDING 2: ON THE BEACH",
  "Dead Space",
  "Dead Space Digital Deluxe Edition",
  "Demon Slayer -Kimetsu no Yaiba- The Hinokami",
  "Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles Deluxe Edition",
  "Detroit: Become Human",
  "Detroit: Become Human Digital Deluxe Edition",
  "Destroy All Humans! - Jumbo Pack",
  "Devil May Cry 4 Special Edition",
  "Devil May Cry 5 + Vergil",
  "Devil May Cry 5 Deluxe + Vergil",
  "Devil May Cry 5 Special Edition",
  "Devil May Cry HD Collection & 4SE Bundle",
  "Diablo III: Eternal Collection",
  "Diablo® IV",
  "Diablo® IV - Expansion Bundle",
  "Diablo® IV - Standard Edition",
  "Diablo® Prime Evil Collection",
  "DIRT 5",
  "DiRT Rally 2.0",
  "DiRT Rally 2.0 - Game of the Year Edition",
  "Dishonored 2",
  "Dishonored® Definitive Edition",
  "DmC Devil May Cry: Definitive Edition",
  "DOOM",
  "DOOM Eternal Deluxe Edition",
  "DOOM Eternal Standard Edition",
  "DOOM: The Dark Ages",
  "Dragon Age™: Inquisition - Game of the Year Edition",
  "DRAGON BALL FighterZ",
  "DRAGON BALL FighterZ - FighterZ Edition",
  "DRAGON BALL XENOVERSE",
  "DRAGON BALL XENOVERSE 2",
  "DRAGON BALL XENOVERSE 2 Deluxe Edition",
  "DRAGON BALL XENOVERSE 2 Special Edition",
  "DRAGON BALL Z: KAKAROT",
  "DRAGON BALL Z: KAKAROT Deluxe Edition",
  "DRAGON BALL Z: KAKAROT DAIMA EDITION",
  "DRAGON BALL Z: KAKAROT Legendary Edition",
  "DRAGON BALL: Sparking! ZERO",
  "DRAGON BALL: Sparking! ZERO Deluxe Edition",
  "Dragon's Dogma: Dark Arisen",
  "Dying Light",
  "Dying Light - Enhanced Edition",
  "Dying Light 2 Stay Human",
  "Dying Light 2 Stay Human: Digital Extras Edition",
  "Dying Light Collection",
  "Dying Light Definitive Edition",
  "Dying Light: The Beast",
  "Dying Light: The Following - Enhanced Edition",
  "EA STAR WARS™ TRIPLE BUNDLE",
  "ELDEN RING",
  "Evil West",
  "F1® 24",
  "F1® 24 Champions Edition",
  "F1® 25",
  "F1® Manager 2024 Deluxe Edition",
  "Fallout 4",
  "Fallout 4: Game of the Year Edition",
  "Fallout 76",
  "FAR CRY 4 + FAR CRY PRIMAL BUNDLE",
  "Far Cry 4 - Gold Edition",
  "Far Cry 5",
  "Far Cry 5 + New Dawn Complete",
  "Far Cry Insanity Bundle",
  "Far Cry New Dawn",
  "FAR CRY PRIMAL - APEX EDITION",
  "Far Cry® 4",
  "Far Cry® 5 + Far Cry® New Dawn Ultimate Edition",
  "Far Cry® 5 Gold Edition",
  "Far Cry® 6 Deluxe Edition",
  "Far Cry® 6 Game of the Year Edition",
  "Far Cry® Primal",
  "FAR CRY®6 Gold Edition",
  "Farming Simulator 22",
  "FC™ 25 Standard Edition",
  "FC™ 26 Standard Edition",
  "FINAL FANTASY VII REBIRTH",
  "FINAL FANTASY VII REMAKE",
  "FINAL FANTASY XV ROYAL EDITION",
  "FINAL FANTASY XVI",
  "Five Nights at Freddy's",
  "Five Nights at Freddy's 2",
  "Five Nights at Freddy's: Secret of the Mimic",
  "Five Nights at Freddy's: Security Breach",
  "Flight Sim 2025",
  "Forza Horizon 5 Deluxe Edition",
  "Forza Horizon 5 Standard Edition",
  "FOR HONOR",
  "Gang Beasts",
  "Gears of War: Reloaded",
  "Ghost of Tsushima DIRECTOR’S CUT",
  "Ghost of Yōtei™",
  "Goat Simulator",
  "Goat Simulator 3",
  "Goat Simulator: Remastered",
  "God of War III Remastered",
  "God of War Ragnarök",
  "God of War Ragnarök Digital Deluxe Edition",
  "God of War™ (2018)",
  "God of War™ Digital Deluxe Edition",
  "God of War Sons of Sparta",
  "Gotham Knights",
  "Grand Theft Auto V NEW GEN (PS5)",
  "Grand Theft Auto: The Trilogy – The Definitive Edition",
  "Gran Turismo® 7",
  "Green Hell",
  "GRID Legends",
  "Grounded",
  "GTA V",
  "Hazelight Bundle",
  "Hell is Us",
  "Hell Let Loose",
  "HELLDIVERS™: Super-Earth Ultimate Edition",
  "HELLDIVERS™️ 2",
  "Hello Neighbor 2",
  "Hi-Fi RUSH",
  "Hitman HD Enhanced Collection",
  "HITMAN World of Assassination",
  "HITMAN World of Assassination - Deluxe Edition",
  "HITMAN World of Assassination Part One",
  "Hogwarts Legacy",
  "Hogwarts Legacy: Digital Deluxe Edition",
  "Hogwarts Legacy + Harry Potter: Quidditch Champions Deluxe Editions Bundle",
  "Hollow Knight Voidheart Edition",
  "Hollow Knight: Silksong",
  "Horizon Forbidden West™",
  "Horizon Forbidden West™ Complete Edition",
  "Horizon Zero Dawn: Complete Edition",
  "Horizon Zero Dawn™ Remastered",
  "HOT WHEELS UNLEASHED™",
  "Human: Fall Flat",
  "Hunting Simulator 2",
  "Immortals of Aveum™",
  "INAZUMA ELEVEN: Victory Road",
  "Indiana Jones and the Great Circle",
  "inFAMOUS Second Son™",
  "Injustice™ 2",
  "Injustice™ 2 - Legendary Edition",
  "INSIDE",
  "Insurgency: Sandstorm",
  "It Takes Two",
  "JoJo's Bizarre Adventure: All-Star Battle R",
  "Jujutsu Kaisen Cursed Clash",
  "Jurassic World Evolution 2: Deluxe Edition",
  "Jurassic World Evolution 3",
  "Jurassic World Evolution Deluxe Edition",
  "Jurassic World Evolution: Jurassic Park Edition",
  "Just Cause 3: XXL Edition",
  "Just Cause 4: Reloaded",
  "Just Dance 2025 Edition",
  "Kena: Bridge of Spirits",
  "Killing Floor 3",
  "KILLZONE™ SHADOW FALL",
  "Kingdom Come: Deliverance II",
  "Kingdom Come: Deliverance Royal Edition",
  "Knack 2",
  "L. A. Noire",
  "LEGO® Batman™ 3: Beyond Gotham Deluxe Edition",
  "LEGO® CITY Undercover",
  "LEGO® DC Heroes & Villains Bundle",
  "LEGO® DC Super-Villains",
  "LEGO® DC Super-Villains Deluxe Edition",
  "LEGO® Harry Potter™ Collection",
  "LEGO® Jurassic World™",
  "LEGO® Marvel Collection",
  "LEGO® Marvel Super Heroes 2",
  "LEGO® Marvel Super Heroes 2 Deluxe Edition",
  "LEGO® Marvel’s Avengers",
  "LEGO® Marvel’s Avengers Deluxe Edition",
  "LEGO® Marvel™ Super Heroes",
  "LEGO® Star Wars™: The Force Awakens",
  "LEGO® Star Wars™:The Skywalker Saga Deluxe Edition",
  "LEGO® The Incredibles",
  "LEGO® Worlds",
  "Lies of P",
  "Life is Strange Remastered Collection",
  "Little Nightmares",
  "Little Nightmares I & II",
  "Little Nightmares II",
  "Little Nightmares III",
  "Lords of the Fallen Deluxe Edition",
  "Mad Max",
  "MADiSON",
  "Mafia II: Definitive Edition",
  "Mafia III: Definitive Edition",
  "Mafia: Definitive Edition",
  "Mafia: The Old Country",
  "Mafia: Trilogy",
  "MARVEL Cosmic Invasion",
  "MARVEL vs. CAPCOM Fighting Collection: Arcade Classics",
  "Marvel vs. Capcom: Infinite - Standard Edition",
  "Marvel's Guardians of the Galaxy",
  "Marvel's Spider-Man: Game of the Year Edition",
  "Marvel’s Spider-Man: Game of the Year Edition (INGLES)",
  "Marvel's Spider-Man: Miles Morales",
  "Marvel's Spider-Man: Miles Morales Ultimate Edition",
  "Marvel’s Spider-Man 2",
  "Marvel’s Spider-Man 2 Digital Deluxe Edition",
  "Marvel's Spider-Man Remastered",
  "Mass Effect™ Legendary Edition",
  "Mass Effect™: Andromeda – Deluxe Recruit Edition",
  "Max Payne®",
  "Mega Man X Legacy Collection",
  "Metal Gear Solid V: The Definitive Experience",
  "METAL GEAR SOLID Δ: SNAKE EATER",
  "METAL GEAR SOLID: MASTER COLLECTION Vol.1",
  "METAL SLUG 3",
  "METAL SLUG ANTHOLOGY™",
  "Metaphor: ReFantazio",
  "Metro 2033 Redux",
  "Metro Exodus",
  "Metro Redux",
  "Metro Saga Bundle",
  "Microsoft Flight Simulator 2024- Standard Edition",
  "Middle-earth™: Shadow of Mordor™ - Game of the Year Edition",
  "Middle-earth™: Shadow of War™",
  "Middle-earth™: Shadow of War™ Definitive Edition",
  "Middle-earth™: The Shadow Bundle",
  "Minecraft",
  "MLB® The Show™ 24",
  "MLB® The Show™ 25",
  "MLB® The Show™ 25 Edicion Deluxe",
  "MLB® The Show™ 26",
  "Monster Energy Supercross - The Official Videogame 6",
  "Monster Hunter Rise + Sunbreak",
  "Monster Hunter Rise",
  "Monster Hunter World: Iceborne Master Edition",
  "Monster Hunter Wilds",
  "MONSTER HUNTER: WORLD™",
  "Mortal Kombat 11",
  "Mortal Kombat 11 (subtitulado)",
  "Mortal Kombat 11 Ultimate (LATINO)",
  "Mortal Kombat 11 ULTIMATE (SUBTITULADO)",
  "Mortal Kombat 11 Ultimate + Injustice 2 Leg. Edition Bundle",
  "MORTAL KOMBAT X",
  "Mortal Kombat XL",
  "Mortal Kombat™ 1: Definitive Edition",
  "Mortal Kombat™ 1: Khaos Reigns Kollection",
  "Mortal Kombat™️ 1",
  "MotoGP™22",
  "MotoGP™24",
  "MotoGP™25",
  "MOUSE: P.I. For Hire",
  "MudRunner - American Wilds Edition",
  "MXGP3 - The Official Motocross Videogame",
  "MX vs ATV Legends",
  "NARUTO SHIPPUDEN: Ultimate Ninja STORM 4 Road to Boruto",
  "NARUTO SHIPPUDEN: Ultimate Ninja STORM Trilogy",
  "NARUTO SHIPPUDEN™: Ultimate Ninja® STORM 4",
  "NARUTO SHIPPUDEN: Ultimate Ninja STORM Legacy",
  "NARUTO TO BORUTO: SHINOBI STRIKER",
  "NARUTO X BORUTO Ultimate Ninja STORM CONNECTIONS",
  "NBA 2K24 Baller Edition",
  "NBA 2K25 Tournament Edition",
  "NBA 2K26",
  "Need for Speed™",
  "Need for Speed™ Deluxe Edition",
  "Need for Speed™ Heat",
  "Need for Speed™ Heat Deluxe Edition",
  "Need for Speed™ Hot Pursuit Remastered",
  "Need for Speed™ Payback",
  "Need for Speed™ Payback - Deluxe Edition",
  "Need for Speed™ Rivals",
  "Need for Speed™ Rivals: Complete Edition",
  "Need for Speed™ Ultimate Bundle",
  "Need for Speed™ Unbound",
  "Need for Speed™ Unbound Palace Edition",
  "NieR Replicant",
  "NieR: Automata™ Game of the YoRHa Edition",
  "NINJA GAIDEN 4",
  "NINJA GAIDEN: Master Collection",
  "No Man's Sky",
  "ON THE ROAD - The Truck Simulator",
  "ONE PIECE ODYSSEY Deluxe Edition",
  "Outlast",
  "Outlast 2",
  "Outlast: Bundle of Terror",
  "Overcooked",
  "Overcooked! + Overcooked! 2",
  "Overcooked! 2",
  "Overcooked! All You Can Eat",
  "PAC-MAN WORLD 2 Re-PAC",
  "Palworld",
  "PAW Patrol Mighty Pups Save Adventure Bay",
  "PAYDAY 2: CRIMEWAVE EDITION",
  "PAYDAY 3",
  "Persona 3 Reload",
  "Persona 4 Golden",
  "Persona 5",
  "Persona 5 Royal",
  "Persona 5: Ultimate Edition",
  "Phasmophobia",
  "Planet Zoo",
  "Plants vs. Zombies: Battle for Neighborville™",
  "Plants vs. Zombies: Battle for Neighborville™ Deluxe Edition",
  "Plants vs. Zombies™ Garden Warfare",
  "Plants vs. Zombies™ Garden Warfare 2: Standard Edition",
  "Plants vs. Zombies™: Replanted",
  "Police Simulator: Patrol Officers",
  "Poppy Playtime: Chapter 1",
  "Poppy Playtime: Chapter 2",
  "Poppy Playtime: Chapter 4",
  "PRAGMATA",
  "Prince of Persia The Lost Crown",
  "RACCOON CITY EDITION",
  "Ratchet & Clank: Rift Apart",
  "Ratchet & Clank™",
  "Rayman® Legends",
  "Ready or Not",
  "Ready or Not: Digital Deluxe Edition",
  "Red Dead Redemption",
  "Red Dead Redemption & Red Dead Redemption 2 Bundle",
  "Red Dead Redemption 2",
  "Red Dead Redemption 2: Ultimate Edition",
  "Remnant II® - Deluxe Edition",
  "Resident Evil",
  "Resident Evil 0",
  "RESIDENT EVIL 2",
  "RESIDENT EVIL 2 Deluxe Edition",
  "RESIDENT EVIL 3",
  "Resident Evil 4 Remake",
  "Resident Evil 4 Gold Edition",
  "Resident Evil 4 (2005)",
  "RESIDENT EVIL 5",
  "Resident Evil 6",
  "RESIDENT EVIL 7 biohazard Gold Edition",
  "Resident Evil 7 Gold Edition & Village Gold Edition",
  "Resident Evil Remake Trilogy",
  "Resident Evil Requiem",
  "RESIDENT EVIL REVELATIONS",
  "Resident Evil Revelations 1 & 2 Bundle",
  "Resident Evil Revelations 2 Deluxe Edition",
  "RESIDENT EVIL TRIPLE PACK",
  "Resident Evil Village Gold Edition",
  "Resident Evil™ Code: Veronica X",
  "Returnal",
  "RIDE 5",
  "Riders Republic™",
  "Riders Republic™ 360 Edition",
  "RiMS Racing",
  "Rise of the Tomb Raider: 20 Year Celebration",
  "RoboCop: Rogue City",
  "Rugby 22",
  "Sackboy: A Big Adventure",
  "Sea of Thieves",
  "SAROS",
  "SEGA Genesis Classics",
  "Sekiro™️: Shadows Die Twice - Game of the Year Edition",
  "SHADOW OF THE COLOSSUS",
  "Sifu",
  "SILENT HILL 2",
  "SILENT HILL f",
  "Sleeping Dogs™ Definitive Edition",
  "Slime Rancher",
  "Slime Rancher 2",
  "Sniper Elite 4",
  "Sniper Elite 4 Deluxe Edition",
  "Sniper Elite 5",
  "Sniper Elite: Resistance",
  "Sniper Ghost Warrior 3",
  "Sniper Ghost Warrior Contracts 1 & 2 Double Pack",
  "SnowRunner",
  "SnowRunner - 1-Year Anniversary Edition",
  "Sonic Colours: Ultimate - Digital Deluxe",
  "SONIC FORCES Digital Standard Edition",
  "Sonic Frontiers",
  "Sonic Mania",
  "Sonic Origins",
  "Sonic Racing: CrossWorlds",
  "SONIC SUPERSTARS",
  "SONIC X SHADOW GENERATIONS",
  "SOUTH PARK: SNOW DAY!",
  "South Park: The Video Game Collection",
  "South Park™: The Fractured but Whole™",
  "South Park™: The Stick of Truth™",
  "Split Fiction",
  "Spyro™ Reignited Trilogy",
  "STAR WARS Jedi: Fallen Order™",
  "STAR WARS Jedi: Fallen Order™️ Deluxe Edition",
  "STAR WARS Jedi: Survivor™",
  "Star Wars Outlaws Deluxe Edition",
  "STAR WARS™ Battlefront™ II",
  "STAR WARS™ Battlefront™ II: Celebration Edition",
  "STAR WARS™ Battlefront™ Ultimate Edition",
  "STAR WARS™ Jedi Cross-Gen Bundle Edition",
  "Stellar Blade™",
  "Stray",
  "STEEP",
  "Street Fighter 30th Anniversary Collection",
  "Street Fighter V: Champion Edition",
  "Street Fighter™ 6",
  "Subnautica: Below Zero",
  "Suicide Squad: Kill the Justice League",
  "Taxi Life - Supporter Edition",
  "Taxi Life: A City Driving Simulator",
  "Team Sonic Racing",
  "Teenage Ninja Turtles: Shredder's Revenge",
  "TEKKEN 7",
  "TEKKEN 7 - Definitive Edition",
  "TEKKEN 7 - Originals Edition",
  "TEKKEN 8",
  "TEKKEN 8 Advanced Edition",
  "Tennis World Tour",
  "Tennis World Tour: Roland-Garros Edition",
  "Terraria",
  "The Callisto Protocol™ - Digital Deluxe Edition",
  "The Crew® 2 Gold Edition",
  "The Crew® 2 Special Edition",
  "The Crew Motorfest",
  "The Crew Motorfest Deluxe Edition",
  "The Elder Scrolls IV: Oblivion Remastered",
  "The Elder Scrolls V: Skyrim Special Edition",
  "The Evil Within",
  "The Evil Within 2",
  "The Evil Within Digital Bundle",
  "THE FOREST",
  "The Heavy Rain™ & BEYOND: Two Souls™ Collection",
  "THE KING OF FIGHTERS '99",
  "THE KING OF FIGHTERS XV",
  "The Last of Us Part II",
  "The Last of Us Part II Digital Deluxe Edition",
  "The Last of Us™ Complete",
  "The Last of Us™ Part I",
  "The Last of Us™ Part II Remastered",
  "The Last Of Us™ Remastered",
  "The Last of Us™: Left Behind (Standalone)",
  "The LEGO® Games Bundle",
  "The Nioh Collection",
  "The Outlast Trials",
  "The Quarry",
  "The Smurfs - Mission Vileaf",
  "The Walking Dead: The Telltale Definitive Series",
  "The Witcher 3: Wild Hunt",
  "The Witcher 3: Wild Hunt – Complete Edition",
  "theHunter: Call of the Wild™",
  "Titanfall® 2 Standard Edition",
  "Titanfall® 2: Ultimate Edition",
  "Tom Clancy's Ghost Recon® Breakpoint",
  "Tom Clancy's Ghost Recon® Breakpoint Deluxe Edition",
  "Tom Clancy's Rainbow Six Siege Deluxe Edition",
  "TOM CLANCY'S THE DIVISION",
  "Tom Clancy's The Division 2",
  "Tom Clancy’s Ghost Recon® Wildlands - Standard Edition",
  "Tomb Raider I-III Remastered Starring Lara Croft",
  "Tomb Raider IV-VI Remastered",
  "Tomb Raider: Definitive Edition",
  "Tomb Raider: Definitive Survivor Trilogy",
  "Tony Hawk's™ Pro Skater™ 1 + 2",
  "Tony Hawk's™ Pro Skater™ 3 + 4 - Cross-Gen Edition",
  "TopSpin 2K25",
  "Tropico 6",
  "Truck Driver: The American Dream",
  "Truck Simulator 25 - American Driver",
  "UFC® 4 Deluxe Edition",
  "UFC® 5",
  "UFC® 5 Deluxe Edition",
  "UFC®️ 5 Ultimate Edition",
  "Ultimate Marvel vs. Capcom 3",
  "UNCHARTED 4: A Thief’s End & UNCHARTED: The Lost Legacy Digital Bundle",
  "UNCHARTED: Legacy of Thieves Collection",
  "UNCHARTED™ The Nathan Drake Collection",
  "Undisputed",
  "Unravel Two",
  "Unravel Yarny Bundle",
  "Until Dawn™ 2015",
  "Warhammer 40,000: Space Marine 2",
  "Watch Dogs 1 + Watch Dogs 2 Gold Editions Bundle",
  "Watch Dogs 2 - Deluxe Edition",
  "Watch Dogs 2 - Gold Edition",
  "Watch Dogs: Legion",
  "Watch Dogs: Legion - Deluxe Edition",
  "Watch Dogs® 2 - Deluxe Edition",
  "Watch Dogs®2",
  "Wobbly Life",
  "Wolfenstein: Alt History Collection",
  "World War Z: Aftermath",
  "WRC 10 - Deluxe Edition",
  "WRC 10 FIA World Rally Championship",
  "WRC 9 FIA World Rally Championship PS4 & PS5",
  "WRC Collection",
  "WRC Generations - Fully Loaded Edition",
  "WRC Generations – The FIA WRC Official Game",
  "Wreckfest",
  "WWE 2K Battlegrounds",
  "WWE 2K25 Standard Edition",
  "WWE 2K26 Standard Edition",
  "Zombie Army 4: Dead War",
  "Zombie Army Trilogy"
];

function normalize(title) {
  return title
    .toLowerCase()
    .replace(/[™®©]/g, '')
    .replace(/\s+/g, ' ')
    .replace(/[^a-z0-9]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function cleanTitle(name) {
  let title = name;
  title = title.replace(/\(([^)]+)\)/g, '');
  title = title.split(' (PS')[0].split(' | Alquiler')[0].split(' | P2')[0];
  title = title.replace(/[💳⭐🔥⚡🔰🟢]/g, '');
  title = title.replace(/(Gold|Deluxe|Standard|Ultimate|Complete|Definitive|Legacy|GOTY|Game of the Year|Special|Legendary|Enhanced|Remastered|Remake|Eternal)\s+Edition/gi, '');
  title = title.replace(/\b(Gold|Deluxe|Ultimate|Complete|Definitive|Remastered|Remake|Eternal|Collection)\b/gi, '');
  title = title.replace(/Alquiler\s+\d+\s+días/gi, '');
  title = title.replace(/Alquiler/gi, '');
  title = title.replace(/Rent\s+\d+\s+days/gi, '');
  title = title.replace(/Rent/gi, '');
  return title.trim().toLowerCase().replace(/\s+/g, ' ');
}

async function main() {
  const catalogPath = 'C:\\Users\\pc\\Downloads\\seller_432476_all_products.json';
  const catalogData = JSON.parse(fs.readFileSync(catalogPath, 'utf8'));
  const sellerProducts = catalogData.product || [];

  // Group matched listings by game and category, then keep only the cheapest one!
  const cheapestMatches = {};

  for (const game of userGamesList) {
    const normGame = normalize(game);
    for (const sp of sellerProducts) {
      const normSp = normalize(sp.name);
      
      if (normSp.includes(normGame) || normGame.includes(normSp)) {
        const nameLower = sp.name.toLowerCase();
        const price = parseFloat(sp.price) || 0;
        
        // Check console category
        if (nameLower.includes('ps5')) {
          const key = `${cleanTitle(game)}_PS5`;
          if (!cheapestMatches[key] || price < cheapestMatches[key].price) {
            cheapestMatches[key] = { game, product: sp, price, category: 'PS5' };
          }
        }
        if (nameLower.includes('ps4')) {
          const key = `${cleanTitle(game)}_PS4`;
          if (!cheapestMatches[key] || price < cheapestMatches[key].price) {
            cheapestMatches[key] = { game, product: sp, price, category: 'PS4' };
          }
        }
      }
    }
  }

  const selectedMatches = Object.values(cheapestMatches);
  console.log(`Deduplicated: Found ${selectedMatches.length} unique cheapest game listings to import.`);

  // Check how many of these selected matches are already in the DB
  const targets = selectedMatches.map(m => `${m.product.id}-${m.category}`);
  const existingProducts = await prisma.product.findMany({
    where: {
      id: { in: targets }
    },
    select: { id: true }
  });

  const existingSet = new Set(existingProducts.map(p => p.id));
  
  let newCount = 0;
  let inDbCount = 0;
  const listToImport = [];

  for (const m of selectedMatches) {
    const key = `${m.product.id}-${m.category}`;
    if (existingSet.has(key)) {
      inDbCount++;
    } else {
      newCount++;
      listToImport.push(m);
    }
  }

  console.log(`Deduplicated matching details:`);
  console.log(`- Already in Database: ${inDbCount}`);
  console.log(`- New (to import): ${newCount}`);
  
  // Save deduplicated import list to a JSON file so the importer script can read it directly!
  fs.writeFileSync('C:\\Users\\pc\\Downloads\\cheapest_import_list.json', JSON.stringify(listToImport, null, 2));
  console.log('Saved cheapest import list to C:\\Users\\pc\\Downloads\\cheapest_import_list.json');
}

main()
  .then(() => prisma.$disconnect())
  .catch(e => {
    console.error(e);
    prisma.$disconnect();
  });
